import {
  Airplane, Barbell, Basket, Bathtub, Bed, Bicycle, Books, BookOpen, Bread, Brain, Briefcase, Broom, Calendar, CalendarCheck, Camera,
  Campfire, Car, Carrot, Cat, ChartLineUp, ChatCircle, CheckSquare, Circle, Clock, Coffee, Coins, Code, CookingPot, Cookie, CreditCard,
  Dog, DeviceMobileSlash, Drop, Envelope, Eyeglasses, FirstAidKit, Fish, Flag, Flame, FlowerLotus, ForkKnife, GameController, Gift,
  GraduationCap, Guitar, HandsPraying, Handshake, Headphones, Heart, Heartbeat, Hourglass, House, Laptop, Leaf, Lightbulb, Lightning,
  ListChecks, MapPin, Microphone, Moon, Mountains, MusicNotes, Notebook, PaintBrush, Palette, PencilSimpleLine, Pen, Phone, PianoKeys,
  PiggyBank, Pill, PersonSimpleRun, PersonSimpleSwim, PersonSimpleTaiChi, Plant, PuzzlePiece, Recycle, Scissors, ShieldCheck, Shower,
  ShoppingCart, Smiley, Snowflake, Sneaker, Sparkle, Star, Sun, SunHorizon, Target, Timer, Tooth, Translate, Trash, Tree, Trophy, Users,
  Wallet, WashingMachine, Wind, Bank,
  type Icon,
} from '@phosphor-icons/react'
import { ledVar, type LedColor } from './palette'

// Curated set for habits, goals and areas: [key, component, search words]. Keys are what the database stores.
const list: [string, Icon, string][] = [
  ['barbell', Barbell, 'workout gym lift strength weights'],
  ['sneaker', Sneaker, 'steps walk shoes run'],
  ['run', PersonSimpleRun, 'running jog cardio exercise'],
  ['bicycle', Bicycle, 'bike cycling ride'],
  ['swim', PersonSimpleSwim, 'swimming pool'],
  ['tai-chi', PersonSimpleTaiChi, 'stretch yoga mobility flexibility'],
  ['heartbeat', Heartbeat, 'health pulse cardio'],
  ['heart', Heart, 'love gratitude care'],
  ['drop', Drop, 'water hydrate glass drink'],
  ['pill', Pill, 'vitamins medicine supplements'],
  ['tooth', Tooth, 'floss teeth brush dental'],
  ['bed', Bed, 'sleep make bed rest'],
  ['moon', Moon, 'sleep night evening'],
  ['sun', Sun, 'morning day sunlight'],
  ['sun-horizon', SunHorizon, 'sunrise wake early'],
  ['lotus', FlowerLotus, 'meditate mindfulness calm breathe'],
  ['brain', Brain, 'focus think mind learn'],
  ['carrot', Carrot, 'vegetables diet eat healthy'],
  ['cooking-pot', CookingPot, 'meal prep cook kitchen'],
  ['fork-knife', ForkKnife, 'food meal eat'],
  ['coffee', Coffee, 'caffeine tea drink'],
  ['cookie', Cookie, 'sugar sweets snack'],
  ['bread', Bread, 'carbs bake food'],
  ['fish', Fish, 'omega seafood protein'],
  ['book-open', BookOpen, 'read pages reading'],
  ['books', Books, 'library study reading'],
  ['notebook', Notebook, 'journal diary notes write'],
  ['pencil', PencilSimpleLine, 'write draft edit'],
  ['pen', Pen, 'sign write letter'],
  ['graduation-cap', GraduationCap, 'study course learn school'],
  ['translate', Translate, 'language words vocabulary'],
  ['music-notes', MusicNotes, 'music song practice'],
  ['guitar', Guitar, 'instrument practice strings'],
  ['piano-keys', PianoKeys, 'instrument piano keyboard'],
  ['microphone', Microphone, 'sing podcast voice speak'],
  ['headphones', Headphones, 'listen audio podcast'],
  ['palette', Palette, 'art color design'],
  ['paint-brush', PaintBrush, 'paint draw create'],
  ['camera', Camera, 'photo picture'],
  ['code', Code, 'program software side project'],
  ['laptop', Laptop, 'work computer deep work'],
  ['briefcase', Briefcase, 'job career office'],
  ['target', Target, 'goal aim focus'],
  ['lightbulb', Lightbulb, 'idea creative think'],
  ['chart-line-up', ChartLineUp, 'growth progress invest stats'],
  ['clock', Clock, 'time schedule'],
  ['timer', Timer, 'focus pomodoro minutes'],
  ['hourglass', Hourglass, 'wait patience time'],
  ['calendar', Calendar, 'date plan'],
  ['calendar-check', CalendarCheck, 'plan tomorrow schedule review'],
  ['check-square', CheckSquare, 'task done todo'],
  ['list-checks', ListChecks, 'checklist tasks routine'],
  ['envelope', Envelope, 'email inbox mail'],
  ['chat', ChatCircle, 'talk message text'],
  ['wallet', Wallet, 'budget money spend'],
  ['piggy-bank', PiggyBank, 'save savings money'],
  ['coins', Coins, 'money finance'],
  ['bank', Bank, 'finance account'],
  ['credit-card', CreditCard, 'spend debt payment'],
  ['phone', Phone, 'call family friends'],
  ['users', Users, 'people friends family social'],
  ['handshake', Handshake, 'network meet deal'],
  ['hands-praying', HandsPraying, 'gratitude prayer thanks'],
  ['smiley', Smiley, 'mood happy smile'],
  ['house', House, 'home tidy chores'],
  ['broom', Broom, 'clean tidy sweep'],
  ['washing-machine', WashingMachine, 'laundry chores'],
  ['plant', Plant, 'garden grow water plants'],
  ['tree', Tree, 'nature outdoors'],
  ['leaf', Leaf, 'nature green eco'],
  ['dog', Dog, 'pet walk'],
  ['cat', Cat, 'pet'],
  ['car', Car, 'drive commute'],
  ['airplane', Airplane, 'travel trip flight'],
  ['map-pin', MapPin, 'place visit location'],
  ['mountains', Mountains, 'hike climb outdoors'],
  ['campfire', Campfire, 'camp outdoors'],
  ['phone-slash', DeviceMobileSlash, 'no phone screen time detox'],
  ['sparkle', Sparkle, 'special bright new'],
  ['star', Star, 'favorite best'],
  ['flame', Flame, 'streak fire energy'],
  ['lightning', Lightning, 'energy fast power'],
  ['trophy', Trophy, 'win achievement'],
  ['flag', Flag, 'milestone finish'],
  ['gift', Gift, 'give present'],
  ['game-controller', GameController, 'play games fun'],
  ['puzzle-piece', PuzzlePiece, 'hobby puzzle'],
  ['shield-check', ShieldCheck, 'safe protect secure'],
  ['first-aid', FirstAidKit, 'health medical care'],
  ['wind', Wind, 'breathe air'],
  ['snowflake', Snowflake, 'cold shower ice'],
  ['shower', Shower, 'cold shower wash'],
  ['bathtub', Bathtub, 'bath relax'],
  ['recycle', Recycle, 'waste eco'],
  ['trash', Trash, 'declutter throw out'],
  ['shopping-cart', ShoppingCart, 'groceries shop'],
  ['basket', Basket, 'groceries shop'],
  ['scissors', Scissors, 'craft cut'],
  ['eyeglasses', Eyeglasses, 'eyes screen rest'],
]

export const habitIcons = list.map(([name, Icon, words]) => ({ name, Icon, words }))
const byName = new Map(habitIcons.map((i) => [i.name, i.Icon]))

/** Habit icons are Phosphor duotone tinted with the habit color. */
export function HabitIcon({ name, color, size = 24 }: { name: string; color: LedColor; size?: number }) {
  const Glyph = byName.get(name) ?? Circle
  return <Glyph size={size} weight="duotone" color={ledVar(color)} aria-hidden="true" />
}
